package com.fujitsu.core.enums;

public enum ConfigProperties {
    URL,
    OVERRIDEREPORTS,
    PASSEDSTEPSSCREENSHOTS,
    FAILEDSTEPSSCREENSHOTS,
    RETRYFAILEDTESTS,
    RUNMODE,
    SELENIUMGRIDURLCHROME,
    SELENIUMGRIDURLFIREFOX,
    SELENIUMGRIDURLEDGE,
    BROWSER
}
